/ {
    chosen {
        zmk,underglow = &underglow;
    };
};

&gpio0 {
    status = "okay";
};

underglow: ws2812 {
    compatible = "worldsemi,ws2812";
    label = "BT60_RGB_UNDERGLOW";
    gpios = <&gpio0 13 GPIO_ACTIVE_HIGH>;
    chain-length = <12>;

    color-mapping = <LED_COLOR_ID_GREEN
                     LED_COLOR_ID_RED
                     LED_COLOR_ID_BLUE>;
    status = "okay";
};
